/**
 * One-off generator for data/versification.ts.
 *
 * Scrapes the authoritative NWT Study Edition (nwtsty) reading pages on
 * wol.jw.org and records, for every book, the highest verse number present in
 * each chapter. The result is the NWT versification used to validate citations.
 *
 * Run:  npx tsx scripts/generateVersification.ts
 *
 * Verse markers on a reading page look like  id="v{book}-{chapter}-{verse}-1".
 */
import { writeFile } from 'node:fs/promises';

import books from '../data/books.js';

const CONCURRENCY = 8;
const HEADERS = {
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36',
  'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
};

async function maxVerse(bookIndex: number, chapter: number): Promise<number> {
  const url = `https://wol.jw.org/en/wol/b/r1/lp-e/nwtsty/${bookIndex}/${chapter}`;
  for (let attempt = 0; attempt < 4; attempt += 1) {
    try {
      const res = await fetch(url, { headers: HEADERS });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const html = await res.text();
      const re = new RegExp(`id="v${bookIndex}-${chapter}-(\\d+)-1"`, 'g');
      let m: RegExpExecArray | null;
      let max = 0;
      while ((m = re.exec(html)) !== null) max = Math.max(max, parseInt(m[1], 10));
      if (max === 0) throw new Error('no verses found');
      return max;
    } catch (err) {
      if (attempt === 3) throw err;
      await new Promise((r) => setTimeout(r, 2 ** attempt * 1000));
    }
  }
  throw new Error('unreachable');
}

async function run(): Promise<void> {
  // Flatten every (book, chapter) into a task list, then drain with a pool.
  const tasks: { bookIndex: number; chapter: number }[] = [];
  for (const book of books) {
    for (let chapter = 1; chapter <= book.chapterCount; chapter += 1) {
      tasks.push({ bookIndex: book.bookIndex, chapter });
    }
  }

  const counts = new Map<number, number[]>();
  for (const book of books) counts.set(book.bookIndex, new Array(book.chapterCount).fill(0));

  let done = 0;
  let next = 0;
  async function worker(): Promise<void> {
    while (next < tasks.length) {
      const task = tasks[next++];
      const verses = await maxVerse(task.bookIndex, task.chapter);
      counts.get(task.bookIndex)![task.chapter - 1] = verses;
      done += 1;
      if (done % 50 === 0 || done === tasks.length) {
        console.log(`  ${done}/${tasks.length}`);
      }
    }
  }
  await Promise.all(Array.from({ length: CONCURRENCY }, () => worker()));

  // Emit a typed lookup keyed by bookIndex.
  const lines = books.map((book) => {
    const arr = counts.get(book.bookIndex)!;
    if (arr.some((v) => v === 0)) throw new Error(`missing verse count in ${book.name}`);
    return `  ${book.bookIndex}: [${arr.join(', ')}], // ${book.name}`;
  });

  const out = `// AUTO-GENERATED by scripts/generateVersification.ts — do not edit by hand.
// NWT Study Edition (nwtsty) verses-per-chapter, scraped from wol.jw.org.
// Keyed by Book.bookIndex; index i holds the verse count of chapter i+1.

const versification: Record<number, number[]> = {
${lines.join('\n')}
};

export default versification;
`;

  await writeFile(new URL('../data/versification.ts', import.meta.url), out.replace(/\n/g, '\r\n'));
  console.log('Wrote data/versification.ts');
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
